apiVersion: apps/v1
kind: Deployment
metadata:
  name: nba-games-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: nba-games-app
  replicas: 3
  template:
    metadata:
      labels:
        app: nba-games-app
    spec:
      containers:
      - name: nba-games-app
        image: nba_games
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: nba-games-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: nba-games-app
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
    nodePort: 30001
